// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Span.Culturio.Packages.Data;

#nullable disable

namespace Span.Culturio.Packages.Migrations
{
    [DbContext(typeof(PackagesDbContext))]
    partial class PackagesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Span.Culturio.Packages.Models.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ValidDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Osnovni paket",
                            ValidDays = 30
                        },
                        new
                        {
                            Id = 2,
                            Name = "Premium paket",
                            ValidDays = 90
                        },
                        new
                        {
                            Id = 3,
                            Name = "Godišnji paket",
                            ValidDays = 365
                        });
                });

            modelBuilder.Entity("Span.Culturio.Packages.Models.Entities.PackageCultureObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableVisits")
                        .HasColumnType("int");

                    b.Property<int>("CultureObjectId")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageCultureObjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableVisits = 5,
                            CultureObjectId = 1,
                            PackageId = 1
                        },
                        new
                        {
                            Id = 2,
                            AvailableVisits = 3,
                            CultureObjectId = 2,
                            PackageId = 1
                        },
                        new
                        {
                            Id = 3,
                            AvailableVisits = 2,
                            CultureObjectId = 3,
                            PackageId = 1
                        },
                        new
                        {
                            Id = 4,
                            AvailableVisits = 10,
                            CultureObjectId = 1,
                            PackageId = 2
                        },
                        new
                        {
                            Id = 5,
                            AvailableVisits = 8,
                            CultureObjectId = 2,
                            PackageId = 2
                        },
                        new
                        {
                            Id = 6,
                            AvailableVisits = 6,
                            CultureObjectId = 3,
                            PackageId = 2
                        },
                        new
                        {
                            Id = 7,
                            AvailableVisits = 30,
                            CultureObjectId = 1,
                            PackageId = 3
                        },
                        new
                        {
                            Id = 8,
                            AvailableVisits = 25,
                            CultureObjectId = 2,
                            PackageId = 3
                        },
                        new
                        {
                            Id = 9,
                            AvailableVisits = 20,
                            CultureObjectId = 3,
                            PackageId = 3
                        });
                });

            modelBuilder.Entity("Span.Culturio.Packages.Models.Entities.PackageCultureObject", b =>
                {
                    b.HasOne("Span.Culturio.Packages.Models.Entities.Package", "Package")
                        .WithMany("PackageCultureObjects")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Span.Culturio.Packages.Models.Entities.Package", b =>
                {
                    b.Navigation("PackageCultureObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
