// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Span.Culturio.Shared.Data;

#nullable disable

namespace Span.Culturio.Shared.Data.Migrations
{
    [DbContext(typeof(CulturioDbContext))]
    partial class CulturioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Span.Culturio.Shared.Models.Entities.CultureObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("AdminUserId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.ToTable("CultureObjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rooseveltov trg 5",
                            AdminUserId = 1,
                            City = "Zagreb",
                            ContactEmail = "kontakt@mimara.hr",
                            Name = "Muzej Mimara",
                            ZipCode = 10000
                        },
                        new
                        {
                            Id = 2,
                            Address = "Trg Republike Hrvatske 15",
                            AdminUserId = 1,
                            City = "Zagreb",
                            ContactEmail = "info@hnk.hr",
                            Name = "Hrvatsko narodno kazalište",
                            ZipCode = 10000
                        },
                        new
                        {
                            Id = 3,
                            Address = "Avenija Dubrovnik 17",
                            AdminUserId = 1,
                            City = "Zagreb",
                            ContactEmail = "kontakt@msu.hr",
                            Name = "Muzej suvremene umjetnosti",
                            ZipCode = 10000
                        });
                });

            modelBuilder.Entity("Span.Culturio.Shared.Models.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ValidDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Osnovni paket",
                            ValidDays = 30
                        },
                        new
                        {
                            Id = 2,
                            Name = "Premium paket",
                            ValidDays = 90
                        },
                        new
                        {
                            Id = 3,
                            Name = "Godišnji paket",
                            ValidDays = 365
                        });
                });

            modelBuilder.Entity("Span.Culturio.Shared.Models.Entities.PackageCultureObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableVisits")
                        .HasColumnType("int");

                    b.Property<int>("CultureObjectId")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CultureObjectId");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageCultureObjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableVisits = 5,
                            CultureObjectId = 1,
                            PackageId = 1
                        },
                        new
                        {
                            Id = 2,
                            AvailableVisits = 3,
                            CultureObjectId = 2,
                            PackageId = 1
                        },
                        new
                        {
                            Id = 3,
                            AvailableVisits = 2,
                            CultureObjectId = 3,
                            PackageId = 1
                        },
                        new
                        {
                            Id = 4,
                            AvailableVisits = 10,
                            CultureObjectId = 1,
                            PackageId = 2
                        },
                        new
                        {
                            Id = 5,
                            AvailableVisits = 8,
                            CultureObjectId = 2,
                            PackageId = 2
                        },
                        new
                        {
                            Id = 6,
                            AvailableVisits = 6,
                            CultureObjectId = 3,
                            PackageId = 2
                        },
                        new
                        {
                            Id = 7,
                            AvailableVisits = 30,
                            CultureObjectId = 1,
                            PackageId = 3
                        },
                        new
                        {
                            Id = 8,
                            AvailableVisits = 25,
                            CultureObjectId = 2,
                            PackageId = 3
                        },
                        new
                        {
                            Id = 9,
                            AvailableVisits = 20,
                            CultureObjectId = 3,
                            PackageId = 3
                        });
                });

            modelBuilder.Entity("Span.Culturio.Shared.Models.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActiveTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("RecordedVisits")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Span.Culturio.Shared.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("User");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@culturio.hr",
                            FirstName = "Admin",
                            LastName = "User",
                            PasswordHash = "$2a$11$tz4JCwuUMuWtSelRA.C5NOISqpWL5E4vBEYaX903GzpMscp2qeCVi",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Span.Culturio.Shared.Models.Entities.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CultureObjectId")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CultureObjectId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Span.Culturio.Shared.Models.Entities.CultureObject", b =>
                {
                    b.HasOne("Span.Culturio.Shared.Models.Entities.User", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("Span.Culturio.Shared.Models.Entities.PackageCultureObject", b =>
                {
                    b.HasOne("Span.Culturio.Shared.Models.Entities.CultureObject", "CultureObject")
                        .WithMany("PackageCultureObjects")
                        .HasForeignKey("CultureObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Span.Culturio.Shared.Models.Entities.Package", "Package")
                        .WithMany("PackageCultureObjects")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CultureObject");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Span.Culturio.Shared.Models.Entities.Subscription", b =>
                {
                    b.HasOne("Span.Culturio.Shared.Models.Entities.Package", "Package")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Span.Culturio.Shared.Models.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Span.Culturio.Shared.Models.Entities.Visit", b =>
                {
                    b.HasOne("Span.Culturio.Shared.Models.Entities.CultureObject", "CultureObject")
                        .WithMany()
                        .HasForeignKey("CultureObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Span.Culturio.Shared.Models.Entities.Subscription", "Subscription")
                        .WithMany("Visits")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CultureObject");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Span.Culturio.Shared.Models.Entities.CultureObject", b =>
                {
                    b.Navigation("PackageCultureObjects");
                });

            modelBuilder.Entity("Span.Culturio.Shared.Models.Entities.Package", b =>
                {
                    b.Navigation("PackageCultureObjects");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Span.Culturio.Shared.Models.Entities.Subscription", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Span.Culturio.Shared.Models.Entities.User", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
