// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Span.Culturio.CultureObjects.Data;

#nullable disable

namespace Span.Culturio.CultureObjects.Migrations
{
    [DbContext(typeof(CultureObjectsDbContext))]
    partial class CultureObjectsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Span.Culturio.CultureObjects.Models.Entities.CultureObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("AdminUserId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CultureObjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rooseveltov trg 5",
                            AdminUserId = 1,
                            City = "Zagreb",
                            ContactEmail = "kontakt@mimara.hr",
                            Name = "Muzej Mimara",
                            ZipCode = 10000
                        },
                        new
                        {
                            Id = 2,
                            Address = "Trg Republike Hrvatske 15",
                            AdminUserId = 1,
                            City = "Zagreb",
                            ContactEmail = "info@hnk.hr",
                            Name = "Hrvatsko narodno kazalište",
                            ZipCode = 10000
                        },
                        new
                        {
                            Id = 3,
                            Address = "Avenija Dubrovnik 17",
                            AdminUserId = 1,
                            City = "Zagreb",
                            ContactEmail = "kontakt@msu.hr",
                            Name = "Muzej suvremene umjetnosti",
                            ZipCode = 10000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
