apiVersion: v1
kind: Service
metadata:
  name: cultureobjects-service
  namespace: culturio
spec:
  selector:
    app: cultureobjects-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
