apiVersion: v1
kind: Secret
metadata:
  name: culturio-secrets
  namespace: culturio
type: Opaque
stringData:
  sa-password: "CulturioPassword123!"
  jwt-secret: "default-jwt-secret-key-min-32-chars!"
  seq-admin-username: "admin"
  seq-admin-password: "Admin123!"
